name: "memos"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  postgres:
    # for more information about this image checkout:
    # https://github.com/11notes/docker-postgres
    image: "11notes/postgres:18"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      backend:
    volumes:
      - "postgres.etc:/postgres/etc"
      - "postgres.var:/postgres/var"
      - "postgres.backup:/postgres/backup"
    tmpfs:
      - "/postgres/run:uid=1000,gid=1000"
      - "/postgres/log:uid=1000,gid=1000"
    restart: "always"

  app:
    depends_on:
      postgres:
        condition: "service_healthy"
        restart: true
    image: "11notes/memos:0.26.2"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      MEMOS_DSN: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable"
    volumes:
      - "memos.var:/memos/var"
    ports:
      - "3000:5230/tcp"
    networks:
      frontend:
      backend:
    restart: "always"

volumes:
  postgres.etc:
  postgres.var:
  postgres.backup:
  memos.var:

networks:
  frontend:
  backend:
    internal: true